### ISSUE TITLE
오타 발견

### ISSUE THREAD

**Issue by jinwonkim93** [V-AIS/pytorch#2]
또는, 이미 존재하는 Tensor를 기반으로 만들 수 있습니다. 이 방법은 이미 존재하는 Tensor의 특성(데이터 타입, Tensor 크기)를 다시 사용합니다. 명확한 이해를 위해 공식 **문저**에서 하나의 예제로 진행한 부분을 두 개의 예제로 살펴보겠습니다.

**Comment by jinwonkim93** [comment]
x = torch.randn_like(**x**, dtype=torch.float64)
print(x)

그전에 x라는 텐서를 생성 안해서 에러가 나네요.

**Comment by jinwonkim93** [comment]
Neural_Network 
네트워크를 통해 입력 프로세스 (설계된 네트워크 구조와 초기화된 가중치에 대해 전방 계산을 의**마**하는 듯 합니다.

**Comment by pacientes** [comment]
x = torch.randn_like(x, dtype=torch.float64)
print(x)

--> 제가 직접 예제 실행 시 작성했던 부분 추가하였습니다.

**Comment by pacientes** [comment]
그 외 코멘트 달아주신 오타 수정하였습니다.
